//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by imageview.rc
//
#define ID_FILE_SETTINGS_EXPLORER       101
#define IDR_FONT_NOTO                   102
#define IDI_ICON_DEFAULT                103
#define IDR_FONT_ROBOTO                 104
#define IDR_ACCELERATORS_EN_UK          104
#define IDC_CURSOR_HAND                 109
#define IDS_AppName                     110
#define IDS_OldCpu                      111
#define IDS_SelectFile                  112
#define IDR_MENU_POPUP                  112
#define IDD_DIALOG_SETTINGS             113
#define IDS_SETTING_TYPE_BOOL           113
#define IDS_SETTING_TYPE_COLOR          114
#define IDD_DIALOG_SETTINGS_MAIN        115
#define IDD_DIALOG_SETTINGS_HOTKEYS     116
#define IDD_DIALOG_SETTINGS_ABOUT       117
#define IDD_DIALOG_SETTINGS_EXPLORER    118
#define IDS_SETTING_TYPE_RANGED         119
#define IDD_DIALOG_SETTINGS_RELAUNCH    120
#define IDS_SETTING_TYPE_ENUM           121
#define IDS_SETTING_NAME_CACHE_SIZE_MB  122
#define IDS_ENUM_FULLSCREEN_STARTUP_FULLSCREEN 123
#define IDS_SETTING_NAME_BORDER_COLOR   124
#define IDS_SETTING_NAME_BACKGROUND_COLOR 125
#define IDD_DIALOG_SETTING_BOOL         125
#define IDS_SETTING_NAME_GRID_ENABLED   126
#define IDS_SETTING_NAME_GRID_COLOR1    127
#define IDD_DIALOG_SETTING_COLOR        127
#define IDS_SETTING_NAME_GRID_COLOR2    128
#define IDS_SETTING_NAME_GRID_SIZE      129
#define IDD_DIALOG_SETTING_ENUM         129
#define IDS_SETTING_NAME_FIXED_GRID     130
#define IDS_SETTING_NAME_GRID_MULTIPLIER 131
#define IDD_DIALOG_SETTING_RANGED       131
#define IDS_SETTING_NAME_SELECT_FILL_COLOR 132
#define IDD_DIALOG_SETTING_SEPARATOR    132
#define IDS_SETTING_NAME_SELECT_OUTLINE_COLOR1 133
#define IDS_SETTING_NAME_SELECT_OUTLINE_COLOR2 134
#define IDS_SETTING_NAME_SELECT_BORDER_WIDTH 135
#define IDS_SETTING_NAME_SELECT_DASH_LENGTH 136
#define IDS_SETTING_NAME_CROSSHAIR_COLOR1 137
#define IDS_SETTING_NAME_CROSSHAIR_COLOR2 138
#define IDS_SETTING_NAME_ZOOM_BUTTON    139
#define IDS_SETTING_NAME_DRAG_BUTTON    140
#define IDS_SETTING_NAME_SELECT_BUTTON  141
#define IDS_SETTING_NAME_REUSE_WINDOW   142
#define IDS_SETTING_NAME_AUTO_PASTE     143
#define IDS_SETTING_NAME_STARTUP_FULLSCREEN 144
#define IDS_SETTING_NAME_SHOW_FULL_FILENAME 145
#define IDS_SETTING_NAME_SHOW_FILENAME  146
#define IDS_SETTING_NAME_EXIF_OPTION    147
#define IDS_SETTING_NAME_ZOOM_MODE      148
#define IDS_ENUM_FULLSCREEN_STARTUP_WINDOWED 149
#define IDS_ENUM_FULLSCREEN_STARTUP_REMEMBER 150
#define IDS_SETTING_NAME_STARTUP_ZOOM_MODE 151
#define IDS_ENUM_MOUSE_BUTTON_LEFT      152
#define IDS_ENUM_MOUSE_BUTTON_RIGHT     153
#define IDS_ENUM_MOUSE_BUTTON_MIDDLE    154
#define IDS_ENUM_SHOW_FILENAME_ALWAYS   155
#define IDS_ENUM_SHOW_FILENAME_BRIEFLY  156
#define IDS_ENUM_SHOW_FILENAME_NEVER    157
#define IDS_ENUM_EXIF_APPLY             158
#define IDS_ENUM_EXIF_IGNORE            159
#define IDS_ENUM_EXIF_PROMPT            160
#define IDS_ENUM_ZOOM_MODE_FIT_TO_WINDOW 161
#define IDS_ENUM_ZOOM_MODE_SHRINK_TO_FIT 162
#define IDS_ENUM_ZOOM_MODE_ONE_TO_ONE   163
#define IDS_ENUM_ZOOM_MODE_REMEMBER     164
#define IDS_FATAL_ERROR                 165
#define IDS_CANT_LOAD_FILE              166
#define IDS_UNKNOWN_FILE_TYPE           167
#define IDS_RESET_SETTINGS              168
#define IDS_CANT_SAVE_FILE              169
#define IDS_FAILED_TO_LOAD_SETTINGS     170
#define IDS_SAVED_FILE                  171
#define IDS_COPIED                      172
#define IDS_KEYNAME_LEFT                173
#define IDS_KEYNAME_RIGHT               174
#define IDS_KEYNAME_UP                  175
#define IDS_KEYNAME_DOWN                176
#define IDS_KEYNAME_COMMA               177
#define IDS_KEYNAME_PERIOD              178
#define IDS_KEYNAME_PAGEUP              179
#define IDS_KEYNAME_PAGEDOWN            180
#define IDS_KEYNAME_CTRL                181
#define IDS_KEYNAME_SHIFT               182
#define IDS_KEYNAME_ALT                 183
#define IDS_OPEN_FILE_OK_BUTTON         184
#define IDS_SETTING_SEPARATOR_BACKGROUND 185
#define IDS_SETTING_SEPARATOR_GRID      186
#define IDS_SETTING_SEPARATOR_SELECT    187
#define IDS_SETTING_SEPARATOR_MOUSE     188
#define IDS_SETTING_SEPARATOR_WINDOW    189
#define IDS_SET_COLOR_FOR               190
#define IDS_ADMIN                       191
#define IDS_ERROR                       192
#define IDS_SETTING_NAME_SELECT_FILL_ALPHA 193
#define IDR_MENU_POPUP_SETTINGS_SPLIT_BUTTON 194
#define IDC_TAB_CONTROL                 1001
#define IDC_SETTINGS_TAB_CONTROL        1001
#define IDC_LIST_HOTKEYS                1002
#define IDC_CHECK_SETTINGS_ALPHA        1003
#define IDC_BUTTON1                     1004
#define IDC_BUTTON_SETTINGS_BACKGROUND_COLOR 1004
#define IDC_SETTINGS_BUTTON_APPLY       1004
#define IDC_BUTTON_ABOUT_COPY           1004
#define IDC_BUTTON_SETTING_COLOR        1004
#define IDC_SETTINGS_EDIT_ABOUT         1005
#define IDC_BUTTON_SETTINGS_RELAUNCH    1009
#define IDC_CHECK_SETTING_BOOL          1011
#define IDC_COMBO_SETTING_ENUM          1012
#define IDC_EDIT1                       1013
#define IDC_STATIC_SETTING_COLOR        1014
#define IDC_STATIC_SETTING_ENUM         1015
#define IDC_STATIC_SETTING_RANGED       1016
#define IDC_EDIT_SETTING_COLOR          1017
#define IDC_STATIC_SETTING_SEPARATOR    1018
#define IDC_SLIDER_SETTING_RANGED       1019
#define IDC_SPLIT_BUTTON_SETTINGS       1023
#define ID_RECENT_FILE_00               30000
#define ID_RECENT_FILE_01               30001
#define ID_RECENT_FILE_02               30002
#define ID_RECENT_FILE_03               30003
#define ID_RECENT_FILE_04               30004
#define ID_RECENT_FILE_05               30005
#define ID_RECENT_FILE_06               30006
#define ID_RECENT_FILE_07               30007
#define ID_RECENT_FILE_08               30008
#define ID_RECENT_FILE_09               30009
#define ID_FILE_LOAD                    40005
#define ID_FILE_SAVE                    40006
#define ID_VIEW_ALPHA                   40008
#define ID_ZOOM_ALL                     40010
#define ID_ZOOM_ORIGINAL                40011
#define ID_ZOOM_FIT                     40012
#define ID_ZOOM_SELECTION               40013
#define ID_ZOOM_1                       40014
#define ID_FILE_NEXT                    40018
#define ID_FILE_PREV                    40019
#define ID_VIEW_SETBACKGROUNDCOLOR      40021
#define ID_ZOOM_SHRINKTOFIT             40024
#define ID_FILE_RECENT                  40025
#define ID_VIEW_GRIDSIZE                40027
#define ID_ZOOM_CENTER                  40028
#define ID_ZOOM_RESETY                  40029
#define ID_VIEW_FULLSCREEN              40030
#define ID_SELECT_ALL                   40032
#define ID_SELECT_NONE                  40033
#define ID_RECENT_DUMMY                 40034
#define ID_VIEW_FIXEDGRID               40035
#define ID_FILE_SETTINGS                40036
#define ID_ZOOM_RESET                   40037
#define ID_COPY                         40038
#define ID_PASTE                        40039
#define ID_EXIT                         40040
#define ID_FILE_OPEN                    40041
#define ID_FILE_PREVIOUS                40042
#define ID_SELECT_CROP                  40043
#define ID_SHOW_SETTINGS                40069
#define ID_VIEW_SETBORDERCOLOR          40075
#define ID_POPUP_REVERT                 40080
#define ID_POPUP_RESET                  40081
#define ID_POPUP_REVERTTOLASTSAVED      40082
#define ID_POPUP_SETTINGS_REVERT        40083
#define ID_POPUP_SETTINGS_LOAD_SAVED    40084
#define ID_POPUP_SETTINGS_RESET_DEFAULT 40085
#define ID_POPUP_SAVESETTINGS           40086
#define ID_POPUP_SETTINGS_SAVE          40087

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        195
#define _APS_NEXT_COMMAND_VALUE         40088
#define _APS_NEXT_CONTROL_VALUE         1024
#define _APS_NEXT_SYMED_VALUE           112
#endif
#endif
