#undef DECL_SETTING_SECTION
#undef DECL_SETTING_BOOL
#undef DECL_SETTING_UINT
#undef DECL_SETTING_COLOR24
#undef DECL_SETTING_COLOR32
#undef DECL_SETTING_ENUM
#undef DECL_SETTING_RANGED
#undef DECL_SETTING_BINARY
